### ISSUE TITLE
插件仓库被DMCA takedown了

### ISSUE THREAD

**Issue by somerui** [libin9iOak/Code#2]

**Comment by libin9iOak** [comment]
是的，官方干的，不是被举报的，一次性疯了一百多个仓库，没办法恢复



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月28日 21:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [libin9iOak/Code] 插件仓库被DMCA takedown了 (Issue #2) |

**Comment by somerui** [comment]
rip
